/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LicenseListRelationFilter } from "../../license/base/LicenseListRelationFilter";
import { ModuleModelListRelationFilter } from "../../moduleModel/base/ModuleModelListRelationFilter";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";

@InputType()
class CompanyWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  address?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => LicenseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LicenseListRelationFilter)
  @IsOptional()
  @Field(() => LicenseListRelationFilter, {
    nullable: true,
  })
  licenses?: LicenseListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ModuleModelListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ModuleModelListRelationFilter)
  @IsOptional()
  @Field(() => ModuleModelListRelationFilter, {
    nullable: true,
  })
  modules?: ModuleModelListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  users?: UserListRelationFilter;
}

export { CompanyWhereInput as CompanyWhereInput };
