/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ModuleModelService } from "../moduleModel.service";
import { ModuleModelCreateInput } from "./ModuleModelCreateInput";
import { ModuleModel } from "./ModuleModel";
import { ModuleModelFindManyArgs } from "./ModuleModelFindManyArgs";
import { ModuleModelWhereUniqueInput } from "./ModuleModelWhereUniqueInput";
import { ModuleModelUpdateInput } from "./ModuleModelUpdateInput";
import { LicenseFindManyArgs } from "../../license/base/LicenseFindManyArgs";
import { License } from "../../license/base/License";
import { LicenseWhereUniqueInput } from "../../license/base/LicenseWhereUniqueInput";

export class ModuleModelControllerBase {
  constructor(protected readonly service: ModuleModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ModuleModel })
  async createModuleModel(
    @common.Body() data: ModuleModelCreateInput
  ): Promise<ModuleModel> {
    return await this.service.createModuleModel({
      data: {
        ...data,

        company: data.company
          ? {
              connect: data.company,
            }
          : undefined,
      },
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ModuleModel] })
  @ApiNestedQuery(ModuleModelFindManyArgs)
  async moduleModels(@common.Req() request: Request): Promise<ModuleModel[]> {
    const args = plainToClass(ModuleModelFindManyArgs, request.query);
    return this.service.moduleModels({
      ...args,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async moduleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    const result = await this.service.moduleModel({
      where: params,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() data: ModuleModelUpdateInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.updateModuleModel({
        where: params,
        data: {
          ...data,

          company: data.company
            ? {
                connect: data.company,
              }
            : undefined,
        },
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.deleteModuleModel({
        where: params,
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/licenses")
  @ApiNestedQuery(LicenseFindManyArgs)
  async findLicenses(
    @common.Req() request: Request,
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<License[]> {
    const query = plainToClass(LicenseFindManyArgs, request.query);
    const results = await this.service.findLicenses(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiryDate: true,
        id: true,

        moduleField: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/licenses")
  async connectLicenses(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LicenseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenses: {
        connect: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/licenses")
  async updateLicenses(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LicenseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenses: {
        set: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/licenses")
  async disconnectLicenses(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() body: LicenseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      licenses: {
        disconnect: body,
      },
    };
    await this.service.updateModuleModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
